export { default as Home }from "./Home"
export  {  default as About} from "./About"
export  {  default as Jobs} from "./Jobs"
export { default as JobDetails } from "./JobDetails"
export { default as NotFound } from "./NotFound"
export { default as Login } from "./Login"
export {default as Dashboard} from "./Dashboard"